import Lean
import PMADLean.Axioms
import PMADLean.Dynamics
import PMADLean.Incompleteness
import PMADLean.Metrics
import PMADLean.PhyslibBridge
import PMADLean.Probability
import PMADLean.Renormalization
import PMADLean.Test
import PMADLean.Vorticity

open Lean Elab Command Meta

/-- Filters namespaces to target your specific PMAD components -/
def isPmadNamespace (n : Name) : Bool :=
  match n.components with
  | .str .anonymous s :: _ => s == "PMADLean"
  | _ => false

/-- Checks if a name corresponds to Lean's automatically generated data type boilerplate -/
def isAutogeneratedBoilerplate (n : Name) : Bool :=
  match n.components.reverse with
  | .str _ s :: _ => 
    s == "recOn" || s == "casesOn" || s == "rec" || s == "cases" || 
    s == "injEq" || s == "ctorIdx" || s == "toCtorIdx" || s == "sizeOf" ||
    s.startsWith "inj" || s.startsWith "noConfusion"
  | _ => false

/-- 
  Safely unrolls a dependent parameter telescope by opening a local context,
  preventing loose De Bruijn 'bvar' panics during expression pretty-printing.
-/
def safeExtractHypotheses (typeExpr : Expr) : MetaM (List String) := do
  forallTelescope typeExpr fun fvars _ => do
    let mut stringList := []
    for fvar in fvars do
      let ldecl ← fvar.fvarId!.getDecl
      let pp ← ppExpr ldecl.type
      let prettyStr := pp.pretty
      stringList := prettyStr :: stringList
    pure stringList.reverse

-- 1. Register the custom syntax rule as a command type
syntax (name := findOverlapsCmd) "#find_hypothesis_overlaps" : command

-- 2. Define the execution rules for our macro syntax block
elab_rules : command

  | `(command | #find_hypothesis_overlaps) => do
    let env ← getEnv
    
    -- Track duplicates by mapping string representations of hypotheses to declaration coordinates
    let mut hypMap : Std.HashMap String (List (Name × String)) := {}
    let mut scannedFiles : Std.HashSet String := {}
    
    let populatedData ← liftTermElabM do
      let mut currentMap := hypMap
      let mut currentFiles := scannedFiles
      let constantsList := env.constants.toList
      
      for (declName, cinfo) in constantsList do
        if isPmadNamespace declName && !declName.isInternal && !isAutogeneratedBoilerplate declName then
          
          -- Resolve source module tracking
          let moduleNameStr := match env.getModuleIdxFor? declName with
            | some idx => s!"{env.header.moduleNames[idx.toNat]!}.lean"
            | none     => "Local Context / Axioms.lean"
          currentFiles := currentFiles.insert moduleNameStr
          
          -- Safely gather all bound parameter types inside the local context block
          let hypSignatures ← safeExtractHypotheses cinfo.type
          
          for hypTypeStr in hypSignatures do
            -- Filter out trivial descriptions to focus strictly on major topological bounds
            if hypTypeStr.length > 25 then
              let currentList := currentMap.getD hypTypeStr []
              currentMap := currentMap.insert hypTypeStr ((declName, moduleNameStr) :: currentList)
              
      pure (currentMap, currentFiles)
      
    let (finalHypMap, finalFiles) := populatedData
    
    logInfo "===================================================="
    logInfo "📁  ACTIVE SOURCE MODULES DETECTED BY LEAN KERNEL"
    logInfo "===================================================="
    for filename in finalFiles.toArray do
      logInfo s!"   • Checked: {filename}"
    logInfo ""

    logInfo "===================================================="
    logInfo "🔬  INTERNAL LOCAL HYPOTHESIS OVERLAP REPORT"
    logInfo "===================================================="
    
    let mut foundOverlap := false
    for (hypTypeStr, occurrences) in finalHypMap.toArray do
      if occurrences.length > 1 then
        foundOverlap := true
        logInfo s!"📍 Shared Hypothesis Structure:\n  {hypTypeStr}"
        logInfo "   Redundantly Used In:"
        for (declName, fileName) in occurrences do
          logInfo s!"     ↳ Module: {fileName} | Definition: {declName}"
        logInfo ""
        
    if !foundOverlap then
      logInfo "🎉 Complete Independence: No overlapping internal local hypotheses detected."

-- 🚀 TRIGGER THE PANIC-PROOF ANALYSIS
#find_hypothesis_overlaps

